[server]
headless = true
port = 5000
address = 0.0.0.0

[theme]
primaryColor = "#22B8CF"
backgroundColor = "#FAFBFF"
secondaryBackgroundColor = "#F1F5FF"
textColor = "#1F2937"
font = "Poppins"

[client]
showErrorDetails = false

[logger]
level = "warning"
