[theme]
base = "light"
primaryColor = "#22B8CF"
backgroundColor = "#FAFBFF"
secondaryBackgroundColor = "#F1F5FF"
textColor = "#1F2937"
font = "Poppins"

[client]
showErrorDetails = false

[logger]
level = "warning"
